#include "server/router.h"
#include "server/static_files.h"
#include "api/encryption.h"
#include "api/decryption.h"
#include "api/password_tools.h"
#include "api/system_monitor.h"
#include "api/port_scanner.h"
#include "utils/json_utils.h"
#include "utils/file_utils.h"
#include <stdexcept>

namespace { Response error(int status,const std::string& message) { Response r; r.status=status; r.body=json_error(message); return r; }
std::unordered_map<std::string,std::string> multipart(const Request& request) { std::unordered_map<std::string,std::string> parts; auto type=request.headers.find("content-type"); if(type==request.headers.end()) return parts; auto marker=type->second.find("boundary="); if(marker==std::string::npos) return parts; std::string boundary="--"+type->second.substr(marker+9); size_t start=0; while((start=request.body.find(boundary,start))!=std::string::npos) { start+=boundary.size(); if(request.body.compare(start,2,"--")==0) break; if(request.body.compare(start,2,"\r\n")==0) start+=2; size_t headers_end=request.body.find("\r\n\r\n",start); if(headers_end==std::string::npos) break; const auto headers=request.body.substr(start,headers_end-start); auto name_pos=headers.find("name=\""); if(name_pos==std::string::npos) { start=headers_end+4; continue; } name_pos+=6; auto name_end=headers.find('"',name_pos); auto value_start=headers_end+4; auto value_end=request.body.find("\r\n"+boundary,value_start); if(value_end==std::string::npos) break; parts[headers.substr(name_pos,name_end-name_pos)]=request.body.substr(value_start,value_end-value_start); auto filename=headers.find("filename=\""); if(filename!=std::string::npos) { filename+=10; auto filename_end=headers.find('"',filename); parts["_filename"]=headers.substr(filename,filename_end-filename); } start=value_end; } return parts; }
int integer(const std::string& value,int fallback) { try{return std::stoi(value);}catch(...){return fallback;} }
bool flag(const std::string& value) { return value=="true"||value=="1"; } }

Response route_request(const Request& request, const std::string& frontend_root) { if(request.path.rfind("/api/",0)!=0) return serve_static_file(request,frontend_root); try { if(request.method=="GET"&&request.path=="/api/system/metrics") { Response r;r.body=system_metrics_json();return r; } if(request.method=="GET"&&request.path=="/api/system/activity-log") { Response r;r.body=system_activity_log_json();return r; } if(request.method!="POST") return error(405,"Use POST for this endpoint."); auto json=parse_json_object(request.body); if(request.path=="/api/encrypt/text") { if(json["text"].empty()||json["password"].empty())return error(400,"Text and password are required."); Response r;r.body="{\"encrypted\":\""+json_escape(encrypt_text(json["text"],json["password"]))+"\"}";return r; } if(request.path=="/api/decrypt/text") { if(json["text"].empty()||json["password"].empty())return error(400,"Encrypted text and password are required."); Response r;r.body="{\"text\":\""+json_escape(decrypt_text(json["text"],json["password"]))+"\"}";return r; } if(request.path=="/api/password/generate") { auto password=generate_password(integer(json["length"],16),flag(json["lowercase"]),flag(json["uppercase"]),flag(json["numbers"]),flag(json["symbols"])); if(password.empty())return error(400,"Choose at least one character type and a length from 4 to 128."); Response r;r.body="{\"password\":\""+json_escape(password)+"\"}";return r; } if(request.path=="/api/password/check"||request.path=="/api/password/attack-simulate") { if(json["password"].empty())return error(400,"A password is required."); Response r;r.body=password_analysis_json(json["password"],std::stod(json.count("attempts_per_second")?json["attempts_per_second"]:"1000000000"));return r; } if(request.path=="/api/scan/ports") { if(json["host"].empty())return error(400,"A target IP address is required."); Response r;r.body=scan_common_ports_json(json["host"]);return r; } if(request.path=="/api/encrypt/file"||request.path=="/api/decrypt/file") { auto form=multipart(request); if(form["file"].empty()||form["password"].empty())return error(400,"A file and password are required."); Response r;r.content_type="application/octet-stream"; const bool encrypt=request.path=="/api/encrypt/file"; r.body=encrypt?encrypt_bytes(form["file"],form["password"]):decrypt_bytes(form["file"],form["password"]); auto name=safe_filename(form["_filename"]); r.headers["Content-Disposition"]="attachment; filename=\""+(encrypt?name+".enc":name.size()>4&&name.substr(name.size()-4)==".enc"?name.substr(0,name.size()-4):"decrypted_"+name)+"\""; return r; } return error(404,"API endpoint not found."); } catch(const std::exception& e) { return error(400,e.what()); } }
